name: Test
on:
  push:
  pull_request:
    branches: ['main']
jobs:
  test_ci:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
    steps:
      - name: Check ref
        run: |
          echo "ref = ${{ github.ref }}"
          echo "head_ref = ${{ github.head_ref }}"
        shell: bash

      - name: Set refs
        id: set_refs
        run: |
          refs=${{ github.ref }}
          if [ ${{ github.event_name == 'pull_request' }} ]; then
            refs=${{ github.head_ref }}
          fi
          echo '::set-output name=refs::$refs'
        shell: bash

      - name: Check out
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ steps.set_refs.outpputs.refs }}

      - name: Python test
        run: |
          import os
          print(os.getenv('LANG'))
          print(os.getenv('NEW_KEY'))
          with open('env_file.txt', mode='w') as f:
            f.write('NEW_KEY "test env"')
        shell: python

      - name: Get env
        run: |
          echo "check env: $NEW_KEY"
          cat env_file.txt
        shell: bash

      - name: Upload artifacts test
        uses: actions/upload-artifact@v2
        with:
          name: test_artifact_${{ github.run_id }}
          path: env_file.txt
          retention-days: 1

  next_job:
    runs-on: ubuntu-latest
    needs: test_ci
    env:
      REPO: ${{ github.repository }}
    steps:
      - name: Download artifacts test
        uses: actions/download-artifact@v2
        with:
          name: test_artifact_${{ github.run_id }}

      - name: Check file
        run: |
          ls -l *.zip
        shell: bash
