name: Test pre-commit
on:
  push:
  pull_request:
    branches: ['main']
jobs:
  test_ci:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
    steps:
      - name: Check ref
        run: |
          echo "ref = ${{ github.ref }}"
          echo "head_ref = ${{ github.head_ref }}"
          echo "${GITHUB_REF#refs/heads/}"
        shell: bash

      - name: Check out
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ steps.set_refs.outpputs.refs }}

      - name: Inst pre-commit
        run: |
          pip3 install pre-commit
          pre-commit --version
        shell: bash

      - name: Code style check
        run: |
          pre-commit run --all
