name: Test
on:
  push:
  pull_request:
    branches: ['main']
jobs:
  test_ci:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
    steps:
      - name: Check ref
        run: |
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
        shell: bash

      - name: Set refs
        id: set_refs
        run: |
          refs=${{ github.ref }}
          if [ ${{ github.event_name == 'pull_request' }} ]; then
            refs=${{ github.head_ref }}
          fi
          echo '::set-output name=refs::$refs'
        shell: bash

      - name: Check out
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.set_refs.outpputs.refs }}

      - name: Display the path
        run: |
          import os
          print(os.environ['PATH'])
        shell: python

      - name: Docker build
        run: echo "dummy"
        shell: bash
