name: Test
on:
  pull_request:
    branches: ['main']
jobs:
  test_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set refs
        id: set_refs
        run: |
          refs=${{ github.ref }}
          if [ ${{ github.event_name == 'pull_request' }} ]; then
            refs=${{ github.head_ref }}
          fi
          echo '::set-output name=refs::$refs'
        shell: bash

      - name: Check out
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ steps.set_refs.outpputs.refs }}

      - name: Create files
        run: |
          mkdir -p "src/sub1" "src/sub2" "src/sub3/sub31"
          echo "file" > src/sub1/test.log
          echo "file" > src/sub2/test.log
          echo "file" > src/sub3/sub33/test.log
          find "src/"

      - name: Move files
        run: |
          mkdir dest
          while read -r test_log; do
            echo ${test_log}
            p_dir=$(dirname ${test_log})
            mkdir -p "dest/${p_dir}"
            mv "${test_log}" "dest/${p_dir}/test_log.txt"
          done < <(find "src/" -name "test.log")
          ls -F
          find "dest/"

#       - name: Check file
#         run: |
#           echo $(md5sum docker/Dockerfile)
