name: Test matrix
on:
  push:
  pull_request:
    branches: ['main']
jobs:
  test_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['main', 'feat_matrix']
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: show ref
        run: |
          echo "work ref ${{ github.ref }}"
          echo "current ref $(git rev-parse --abbrev-ref @)"

      - run: cat docker/Dockerfile

      # - name: Upload logs
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test for job ${{ strategy.job-index }}
      #     path: test-job-${{ strategy.job-index }}.txt
